server:
  port: 8083

spring:
  application:
    name: worker

  datasource:
    url: jdbc:postgresql://localhost:5432/zapflow_db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: worker-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.zapflow.worker.dto.ZapRunMessage
      auto-offset-reset: earliest
      enable-auto-commit: false
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:your-email@gmail.com} # Use env variable
    password: ${MAIL_PASSWORD:your-app-password} # Use env variable
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# Custom configuration
worker:
  processing-delay: 500 # 500ms delay between actions

logging:
  level:
    com.zapflow: INFO
    org.springframework.kafka: DEBUG
  file:
    name: logs/worker.log
  pattern:
    file: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
