server:
  port: 8081

spring:
  application:
    name: hooks

  datasource:
    url: jdbc:postgresql://localhost:5432/zapflow_db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

logging:
  level:
    com.zapflow: INFO
